# Generated by Django 4.0 on 2022-01-13 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coingecko',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epic_vs_usd', models.DecimalField(decimal_places=8, max_digits=32)),
                ('epic_vs_btc', models.DecimalField(decimal_places=8, max_digits=32)),
                ('epic_vs_other', models.JSONField(default=dict)),
            ],
        ),
    ]
