# Generated by Django 4.0 on 2022-01-13 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coingecko_feed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coingecko',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
