# Generated by Django 4.0 on 2021-12-13 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('timestamp', models.IntegerField()),
                ('avg_time', models.IntegerField()),
                ('height', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('reward', models.DecimalField(decimal_places=8, max_digits=32)),
                ('supply', models.IntegerField()),
                ('algo', models.CharField(choices=[('cuckoo', 'Cuckoo'), ('progpow', 'Progpow'), ('randomx', 'Randomx')], max_length=10)),
                ('diff', models.JSONField()),
                ('hash', models.CharField(max_length=128)),
            ],
            options={
                'ordering': ('-height',),
            },
        ),
    ]
