# Generated by Django 4.0 on 2021-12-25 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorer_feed', '0002_remove_block_diff_block_network_hashrate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='network_hashrate',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='block',
            name='target_diffs',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='block',
            name='total_diffs',
            field=models.JSONField(default=dict),
        ),
    ]
