# Generated by Django 4.0 on 2021-12-28 14:49

from django.db import migrations
import unixtimestampfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('explorer_feed', '0003_alter_block_network_hashrate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='datetime',
            field=unixtimestampfield.fields.UnixTimeStampField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='block',
            name='timestamp',
            field=unixtimestampfield.fields.UnixTimeStampField(),
        ),
    ]
