# Generated by Django 4.0 on 2022-04-20 18:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('price', models.JSONField(default=dict)),
                ('volume', models.JSONField(default=dict)),
                ('trades', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ('-timestamp',),
            },
        ),
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('price', models.JSONField(default=dict)),
                ('change', models.JSONField(default=dict)),
                ('volume', models.JSONField(default=dict)),
                ('trades', models.JSONField(default=dict)),
                ('bids', models.JSONField(default=dict)),
                ('asks', models.JSONField(default=dict)),
                ('candles', models.JSONField(default=dict)),
                ('tickers', models.JSONField(default=dict)),
            ],
        ),
    ]
