# Generated by Django 4.0 on 2021-12-25 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VitexUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('btc_price', models.CharField(max_length=128)),
                ('usd_price', models.CharField(max_length=128)),
                ('holders_count', models.IntegerField()),
                ('holders_stats', models.JSONField(default={})),
            ],
        ),
    ]
