# Generated by Django 4.0 on 2022-01-13 12:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitex_feed', '0002_vitexholdersupdate_delete_vitexupdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('price', models.JSONField(default=dict)),
                ('volume', models.JSONField(default=dict)),
                ('trades', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ('-timestamp',),
            },
        ),
        migrations.CreateModel(
            name='Holders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('holders_count', models.IntegerField()),
                ('holders_stats', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ('-timestamp',),
            },
        ),
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('price', models.JSONField(default=dict)),
                ('change', models.JSONField(default=dict)),
                ('volume', models.JSONField(default=dict)),
                ('trades', models.JSONField(default=dict)),
                ('bids', models.JSONField(default=dict)),
                ('asks', models.JSONField(default=dict)),
                ('candles', models.JSONField(default=dict)),
                ('tickers', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ('-timestamp',),
            },
        ),
        migrations.DeleteModel(
            name='VitexHoldersUpdate',
        ),
    ]
