# Generated by Django 4.0 on 2022-01-13 13:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vitex_feed', '0003_history_holders_update_delete_vitexholdersupdate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='update',
            options={},
        ),
        migrations.AlterField(
            model_name='history',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='holders',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='update',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
