# Generated by Django 4.0 on 2022-04-20 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('core_software', models.JSONField(default=dict)),
                ('keybase', models.JSONField(default=dict)),
                ('other', models.JSONField(default=dict)),
                ('tor', models.JSONField(default=dict)),
            ],
        ),
    ]
